[package]
name = "dns-meta"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@dharitri.com>"]
edition = "2021"
publish = false
[dependencies.dns]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.0.4"
